### ISSUE TITLE
bug? index.js:809:18

### ISSUE THREAD

**Issue by Ruuv1337** [codeagon/arborean-apparel#15]
[13:21:59 GMT+0300] ERROR tera-proxy-game: [dispatch] handle: error running hook for S_ABNORMALITY_BEGIN<2>
data: { target: Long { low: 263724575, high: 32768, unsigned: true },
  source: Long { low: 6969696, high: 0, unsigned: true },
  id: 7000005,
  duration: 0,
  unk: 0,
  stacks: 5,
  unk2: 0 }
error: Cannot read property 'toString' of null
    at StateTracker.isMe (\Desktop\tera-proxy\node_modules\tera-state-tracker\index.js:147:31)
    at StateTracker.hook (\Desktop\tera-proxy\node_modules\tera-state-tracker\index.js:323:26)
    at Dispatch.handle (\Desktop\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:598:27)
    at Dispatch.write (\Desktop\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:463:15)
    at DispatchWrapper.toClient (\Desktop\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\dispatchWrapper.js:44:22)
    at Networking.ArboreanApparel.net.on (\Desktop\tera-proxy\bin\node_modules\AA\index.js:809:18)
    at emitThree (events.js:135:13)
    at Networking.emit (events.js:216:7)
    at Interface.readline.createInterface.on (\Desktop\tera-proxy\bin\node_modules\AA\networking.js:17:11)

**Comment by codeagon** [comment]
fixed btw I think
