### ISSUE TITLE
AA issue 

### ISSUE THREAD

**Issue by MellowAly** [codeagon/arborean-apparel#22]
Hello, my friend has been having this issue with AA for a while. We returned w a clean download n all some days ago, but the error persists. 

So basically once entering AA works fine and we can see each others costumes, but as soon as someone changes costume it doesn't apply. Once my friend enters a instance for example any AA changes are gone. (no costumes) 
I'm in no way experienced in code or jazz and neither is my friend ahaah

The type of error that she keeps getting is following:

{ Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TCP.onread (net.js:610:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

love ur work dong

**Comment by codeagon** [comment]
Should be fixed maybe with a smol server update. Let me know if it persists.
